// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/gallery.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{0}
}

type HashFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *HashFilter) Reset() {
	*x = HashFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashFilter) ProtoMessage() {}

func (x *HashFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashFilter.ProtoReflect.Descriptor instead.
func (*HashFilter) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{1}
}

func (x *HashFilter) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type PhotosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Photos []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
}

func (x *PhotosResponse) Reset() {
	*x = PhotosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotosResponse) ProtoMessage() {}

func (x *PhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotosResponse.ProtoReflect.Descriptor instead.
func (*PhotosResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{2}
}

func (x *PhotosResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

type Photo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash         string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Path         string `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	DateTime     string `protobuf:"bytes,3,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	Iso          int32  `protobuf:"varint,4,opt,name=Iso,proto3" json:"Iso,omitempty"`
	ExposureTime string `protobuf:"bytes,5,opt,name=ExposureTime,proto3" json:"ExposureTime,omitempty"`
	XDimension   int32  `protobuf:"varint,6,opt,name=XDimension,proto3" json:"XDimension,omitempty"`
	YDimension   int32  `protobuf:"varint,7,opt,name=YDimension,proto3" json:"YDimension,omitempty"`
	Model        string `protobuf:"bytes,8,opt,name=Model,proto3" json:"Model,omitempty"`
	FNumber      string `protobuf:"bytes,9,opt,name=FNumber,proto3" json:"FNumber,omitempty"`
}

func (x *Photo) Reset() {
	*x = Photo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{3}
}

func (x *Photo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Photo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Photo) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *Photo) GetIso() int32 {
	if x != nil {
		return x.Iso
	}
	return 0
}

func (x *Photo) GetExposureTime() string {
	if x != nil {
		return x.ExposureTime
	}
	return ""
}

func (x *Photo) GetXDimension() int32 {
	if x != nil {
		return x.XDimension
	}
	return 0
}

func (x *Photo) GetYDimension() int32 {
	if x != nil {
		return x.YDimension
	}
	return 0
}

func (x *Photo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Photo) GetFNumber() string {
	if x != nil {
		return x.FNumber
	}
	return ""
}

type PhotoChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PhotoChunk) Reset() {
	*x = PhotoChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoChunk) ProtoMessage() {}

func (x *PhotoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoChunk.ProtoReflect.Descriptor instead.
func (*PhotoChunk) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{4}
}

func (x *PhotoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_gallery_proto protoreflect.FileDescriptor

var file_proto_gallery_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x0a, 0x48, 0x61,
	0x73, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x36, 0x0a, 0x0e,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x73, 0x22, 0xf1, 0x01, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x73, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x49, 0x73, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x78, 0x70, 0x6f,
	0x73, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x58, 0x44, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x58, 0x44,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x59, 0x44, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x59, 0x44,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x46, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x46, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x0a, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xad, 0x01, 0x0a, 0x07, 0x47,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x15, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x11, 0x2e, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a,
	0x0c, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x11, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x1a, 0x11, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x34, 0x0a, 0x16, 0x66, 0x72,
	0x2e, 0x6d, 0x69, 0x63, 0x68, 0x61, 0x65, 0x6c, 0x63, 0x6f, 0x6c, 0x6c, 0x2e, 0x67, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x79, 0x42, 0x0c, 0x47, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gallery_proto_rawDescOnce sync.Once
	file_proto_gallery_proto_rawDescData = file_proto_gallery_proto_rawDesc
)

func file_proto_gallery_proto_rawDescGZIP() []byte {
	file_proto_gallery_proto_rawDescOnce.Do(func() {
		file_proto_gallery_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gallery_proto_rawDescData)
	})
	return file_proto_gallery_proto_rawDescData
}

var file_proto_gallery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gallery_proto_goTypes = []interface{}{
	(*ListFilter)(nil),     // 0: photo.ListFilter
	(*HashFilter)(nil),     // 1: photo.HashFilter
	(*PhotosResponse)(nil), // 2: photo.PhotosResponse
	(*Photo)(nil),          // 3: photo.Photo
	(*PhotoChunk)(nil),     // 4: photo.PhotoChunk
}
var file_proto_gallery_proto_depIdxs = []int32{
	3, // 0: photo.PhotosResponse.photos:type_name -> photo.Photo
	0, // 1: photo.Gallery.GetPhotos:input_type -> photo.ListFilter
	1, // 2: photo.Gallery.GetByHash:input_type -> photo.HashFilter
	1, // 3: photo.Gallery.ContentByHash:input_type -> photo.HashFilter
	2, // 4: photo.Gallery.GetPhotos:output_type -> photo.PhotosResponse
	3, // 5: photo.Gallery.GetByHash:output_type -> photo.Photo
	4, // 6: photo.Gallery.ContentByHash:output_type -> photo.PhotoChunk
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gallery_proto_init() }
func file_proto_gallery_proto_init() {
	if File_proto_gallery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gallery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gallery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gallery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gallery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Photo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gallery_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotoChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gallery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gallery_proto_goTypes,
		DependencyIndexes: file_proto_gallery_proto_depIdxs,
		MessageInfos:      file_proto_gallery_proto_msgTypes,
	}.Build()
	File_proto_gallery_proto = out.File
	file_proto_gallery_proto_rawDesc = nil
	file_proto_gallery_proto_goTypes = nil
	file_proto_gallery_proto_depIdxs = nil
}
