name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: |
            internal/web/pnpm-lock.yaml

      - name: Prepare Vue App
        run: |
          make prepare

      - name: Build Vue App
        run: |
          make build-web

      - name: Install dependencies
        run: |
          go get .

      - name: Build Go App
        run: go build -v ./...

      - name: Test
        run: go test ./...

      - name: Web ESLint
        run: make vue-lint
